name: 'dbt_model'
version: '1.0.0'
config-version: 2

profile: 'dbt_model'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Source company identifiers
  tln_company_code: 'tln'
  tmi_company_code: 'tmi'
  ieg_company_code: 'ieg'

models:
  dbt_model:
    # Staging models - organized by module, views by default
    staging:
      +materialized: view
      +schema: staging
      accounting:
        +tags: ['accounting', 'staging', 'core']
      sales:
        +tags: ['sales', 'staging']
      purchasing:
        +tags: ['purchasing', 'staging']
      inventory:
        +tags: ['inventory', 'staging']
      master:
        +tags: ['master', 'staging']

    # Mart models - tables for analytics consumption
    marts:
      +materialized: table
      +schema: marts
      finance:
        +tags: ['finance', 'mart', 'core']
        +description: "Finance mart - SOURCE OF TRUTH for financial reporting"
      sales:
        +tags: ['sales', 'mart']
      inventory:
        +tags: ['inventory', 'mart']
      purchasing:
        +tags: ['purchasing', 'mart']

seeds:
  dbt_model:
    +schema: seeds

snapshots:
  dbt_model:
    +schema: snapshots
